
create table "public"."_github_pending_installations" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "payload" jsonb not null
);

alter table "public"."_github_pending_installations" enable row level security;

CREATE UNIQUE INDEX _github_pending_installations_pkey ON public._github_pending_installations USING btree (id);

alter table "public"."_github_pending_installations" add constraint "_github_pending_installations_pkey" PRIMARY KEY using index "_github_pending_installations_pkey";

grant delete on table "public"."_github_pending_installations" to "anon";

grant insert on table "public"."_github_pending_installations" to "anon";

grant references on table "public"."_github_pending_installations" to "anon";

grant select on table "public"."_github_pending_installations" to "anon";

grant trigger on table "public"."_github_pending_installations" to "anon";

grant truncate on table "public"."_github_pending_installations" to "anon";

grant update on table "public"."_github_pending_installations" to "anon";

grant delete on table "public"."_github_pending_installations" to "authenticated";

grant insert on table "public"."_github_pending_installations" to "authenticated";

grant references on table "public"."_github_pending_installations" to "authenticated";

grant select on table "public"."_github_pending_installations" to "authenticated";

grant trigger on table "public"."_github_pending_installations" to "authenticated";

grant truncate on table "public"."_github_pending_installations" to "authenticated";

grant update on table "public"."_github_pending_installations" to "authenticated";

grant delete on table "public"."_github_pending_installations" to "service_role";

grant insert on table "public"."_github_pending_installations" to "service_role";

grant references on table "public"."_github_pending_installations" to "service_role";

grant select on table "public"."_github_pending_installations" to "service_role";

grant trigger on table "public"."_github_pending_installations" to "service_role";

grant truncate on table "public"."_github_pending_installations" to "service_role";

grant update on table "public"."_github_pending_installations" to "service_role";

create policy "Admin Only"
on "public"."_github_pending_installations"
to public
using (false);